/*
 * Builder coordinator class.
 *
 * Licensed Materials - Property of IBM 
 * 5724-O03
 * (C) Copyright 2006. IBM Corp. All rights reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 * See WebSphere Portlet Factory ( product id 5724-O03 ) product license for terms and conditions of use. 
 *
 * This Java source file was generated by the WebSphere Portlet Factory.
 *
 * Do not edit generated code within the following comments /*##GENERATED_...
 */
package com.ibm.wef.samples.wizards;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import com.bowstreet.BSConfig;
import com.bowstreet.editor.uitools.coordinator.WebAppBaseCoordinator;
import com.bowstreet.generation.DynamicBuilderInputDefinition;
import com.bowstreet.util.StringUtil;

/**
 * Coordinator implementation
 */
public class ScriptApplicationWizardCoordinator extends WebAppBaseCoordinator
		implements FilenameFilter {

	private static final String SAMPLES_SCRIPTING_WIZARD_PAGES = "/samples/script_builder/wizard_templates"; //$NON-NLS-1$
	private static final String SAMPLES_SCRIPTING = "/samples/apps/"; //$NON-NLS-1$
	private static final String EMPTY = ""; //$NON-NLS-1$
	private static final String HTML = ".html"; //$NON-NLS-1$
	private static final String CSS = ".css"; //$NON-NLS-1$
	private static final String JS = ".js"; //$NON-NLS-1$
	private static final int tHtml = 0;
	private static final int tCss = 1;
	private static final int tJs = 2;
	InputDefinitions defs = new InputDefinitions();
	private HashMap<String, String> htmlChoices;
	private HashMap<String, String> cssChoices;
	private HashMap<String, String> scriptChoices;

	/**
	 * The initialization method is called each time the builder call is opened.
	 * Here you can set defaults, create dynamic pick lists, show/hide/create
	 * inputs.
	 */
	public String initializeInputs(boolean isNewBuilderCall) {
		defs.name = context.findInputDefinition(Constants.Name);
		defs.portletTitle = context.findInputDefinition(Constants.PortletTitle);
		defs.cssFile = context.findInputDefinition(Constants.CssFile);
		defs.htmlFile = context.findInputDefinition(Constants.HtmlFile);
		defs.scriptFile = context.findInputDefinition(Constants.ScriptFile);
		defs.htmlChoices = context.findInputDefinition(Constants.HtmlChoices);
		defs.includeLibrariesOption = context
				.findInputDefinition(Constants.IncludeLibrariesOption);
		defs.libraries = context.findInputDefinition(Constants.Libraries);
		defs.portletAdapter_BuilderCallEnabled = context
				.findInputDefinition(Constants.PortletAdapter_BuilderCallEnabled);
		defs.addServiceProviderSupport = context
				.findInputDefinition(Constants.AddServiceProviderSupport);
		defs.serviceProvider = context
				.findInputDefinition(Constants.ServiceProvider);

		initPickers();
		defs.htmlChoices.setString("empty");
		showDeploymentRelatedFields();

		super.initializeInputs(isNewBuilderCall);

		return null;
	}

	private void showDeploymentRelatedFields() {
		boolean vis = defs.portletAdapter_BuilderCallEnabled.getBoolean();
		defs.portletTitle.setVisible(vis);
		defs.includeLibrariesOption.setVisible(vis);
	}

	/**
	 * This is called whenever any input is changed. NOTE: This method must
	 * return "true" to have UI updated.
	 */
	public boolean processInputChange(DynamicBuilderInputDefinition changed) {
		String changedName = changed.getName().intern();
		if (changedName == Constants.Name) {
			if(!checkFolder(defs.name.getString())){
				context.getDesigner().openError("Application Name", "Application folder already exisits"); //$NON-NLS-1$ //$NON-NLS-2$
				defs.name.setString("");
			}
			return true;
		} else if (changed == defs.portletAdapter_BuilderCallEnabled) {
			showDeploymentRelatedFields();
			return true;
		}
		return false;
	}

	private boolean checkFolder(String name) {
		String destFileDir = BSConfig.getHtmlRootDir() + SAMPLES_SCRIPTING
				+ '/' + name;
		File destFolder = new File(destFileDir);
		// name is no good if the folder already exists
		return !destFolder.exists();
	}

	public void terminate() {
		String htmlChoice = defs.htmlChoices.getString();
		String name = defs.name.getString();
		String htmlFile = getNewFile(htmlChoices.get(htmlChoice), name, tHtml);
		defs.htmlFile.setString(htmlFile);
		if (htmlFile != null) {
			String cssFile = getNewFile(cssChoices.get(htmlChoice), name, tCss);
			defs.cssFile.setString(cssFile);

			String scriptFile = getNewFile(scriptChoices.get(htmlChoice), name,
					tJs);
			defs.scriptFile.setString(scriptFile);
		}
	}

	private String getNewFile(String fileName, String name, int type) {
		String sourceFileDir = BSConfig.getHtmlRootDir()
				+ SAMPLES_SCRIPTING_WIZARD_PAGES + '/';
		String destFileDir = BSConfig.getHtmlRootDir() + SAMPLES_SCRIPTING;
		File appsFolder = new File(destFileDir);
		appsFolder.mkdir();
		destFileDir+= name;
		String childFolder = null;
		File destFolder = new File(destFileDir);
		// if new html file create the folder it shouldn't exist
		if (type == tHtml) {
			destFolder.mkdir();
		}
		// if css file create the folder it shouldn't exist
		if (type == tCss) {
			childFolder = '/' + "css"; //$NON-NLS-1$
			destFileDir += childFolder;
			destFolder = new File(destFileDir);
			destFolder.mkdir();
		} else
		// if js file create the folder it shouldn't exist
		if (type == tJs) {
			childFolder ='/' + "js"; //$NON-NLS-1$
			destFileDir += childFolder;
			destFolder = new File(destFileDir);
			destFolder.mkdir();
		}
		if (fileName != null) {
			File srcFile = new File(sourceFileDir + fileName);
			if (type == tHtml)
				// html page is always index.html so set dest to index.html
				fileName = "index.html"; //$NON-NLS-1$

			String fName = destFileDir + '/' + fileName;
			File destFile = new File(fName);
			try {
				if (destFile.createNewFile()) {
					copyFileUsingStream(srcFile, destFile);
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
			if (childFolder != null)
				return SAMPLES_SCRIPTING + name + childFolder + '/'
						+ fileName;
			else
				return SAMPLES_SCRIPTING +  name + '/' + fileName;
		}
		return null;
	}

	private void copyFileUsingStream(File source, File dest) throws IOException {
		InputStream is = null;
		OutputStream os = null;
		try {
			is = new FileInputStream(source);
			os = new FileOutputStream(dest);
			byte[] buffer = new byte[1024];
			int length;
			while ((length = is.read(buffer)) > 0) {
				os.write(buffer, 0, length);
			}
		} finally {
			is.close();
			os.close();
		}
	}

	static class InputDefinitions {
		DynamicBuilderInputDefinition name;
		DynamicBuilderInputDefinition portletAdapter_BuilderCallEnabled;
		DynamicBuilderInputDefinition portletTitle;
		DynamicBuilderInputDefinition libraries;
		DynamicBuilderInputDefinition includeLibrariesOption;
		DynamicBuilderInputDefinition htmlFile;
		DynamicBuilderInputDefinition htmlChoices;
		DynamicBuilderInputDefinition scriptFile;
		DynamicBuilderInputDefinition cssFile;
		DynamicBuilderInputDefinition addServiceProviderSupport;
		DynamicBuilderInputDefinition serviceProvider;
	}

	static public interface Constants {
		public static final String Name = "Name"; //$NON-NLS-1$
		public static final String PortletAdapter_BuilderCallEnabled = "PortletAdapter_BuilderCallEnabled"; //$NON-NLS-1$
		public static final String PortletTitle = "PortletTitle"; //$NON-NLS-1$
		public static final String Libraries = "Libraries"; //$NON-NLS-1$
		public static final String IncludeLibrariesOption = "IncludeLibrariesOption"; //$NON-NLS-1$
		public static final String HtmlChoices = "HtmlChoices"; //$NON-NLS-1$
		public static final String HtmlFile = "HtmlFile"; //$NON-NLS-1$
		public static final String ScriptFile = "ScriptFile"; //$NON-NLS-1$
		public static final String CssFile = "CssFile"; //$NON-NLS-1$
		public static final String AddServiceProviderSupport = "AddServiceProviderSupport"; //$NON-NLS-1$
		public static final String ServiceProvider = "ServiceProvider"; //$NON-NLS-1$

		// Names of some pages
		public static final String PortletInfoPage = "PortletInfo"; //$NON-NLS-1$
	}

	/*
	 * Initialize the pick list of libraries, by getting a list of HTML files in
	 * a particular folder.
	 */
	private void initPickers() {

		htmlChoices = new HashMap<String, String>();
		cssChoices = new HashMap<String, String>();
		scriptChoices = new HashMap<String, String>();

		// Build list from the files in /samples/script_builder/libraries/
		try {
			File dir = new File(BSConfig.getHtmlRootDir()
					+ SAMPLES_SCRIPTING_WIZARD_PAGES);

			// The accept() method is used to filter the files returned from
			// this method call.
			File[] files = dir.listFiles(this);

			for (int x = 0; x < files.length; x++) {
				if (files[x].getName().endsWith(HTML)) {
					String name = StringUtil.replace(files[x].getName(), HTML,
							EMPTY);
					htmlChoices.put(name, files[x].getName());
				} else if (files[x].getName().endsWith(CSS)) {
					String name = StringUtil.replace(files[x].getName(), CSS,
							EMPTY);
					cssChoices.put(name, files[x].getName());
				} else if (files[x].getName().endsWith(JS)) {
					String name = StringUtil.replace(files[x].getName(), JS,
							EMPTY);
					scriptChoices.put(name, files[x].getName());
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		// System.out.println("fieldChoices: " + fieldChoices);
		ArrayList<String> inputList = new ArrayList<String>(htmlChoices.keySet());
		Collections.sort(inputList);
		updateCombobox(defs.htmlChoices, "listData",
				StringUtil.buildDelimitedString(inputList, ','));
	}

	/*
	 * Updates the specified argument for the Editor of a combo widget editor.
	 * 
	 * @param inputDef The InputDefinition that contains the combo widget
	 * 
	 * @param argumentName The name of the argument to modify (e.g. listData).
	 * 
	 * @param argumentData The new argument value (e.g. A,B,C).
	 */
	private static void updateCombobox(DynamicBuilderInputDefinition inputDef,
			String argumentName, String argumentData) {
		if (inputDef == null || argumentName == null || argumentData == null)
			return;
		@SuppressWarnings("unchecked")
		Map<String, String> m = inputDef.getArguments();
		String listData = m.get(argumentName); //$NON-NLS-1$
		if (listData == null)
			return;
		if (argumentData != null) {
			m.put(argumentName, argumentData);
			int cIndex = argumentData.indexOf(',');
			if (cIndex != -1)
				inputDef.setString(argumentData.substring(0, cIndex));
			else
				inputDef.setString(argumentData);
		}
	}

	@Override
	public boolean accept(File file, String name) {
		if (name.endsWith(HTML) || name.endsWith(CSS) || name.endsWith(JS))
			return true;
		return false;
	}
}
